name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Check Python syntax
      - name: Check Python file
        run: python -m py_compile app.py

      # Build Docker image
      - name: Build Docker image
        run: docker build -t flask-app .

      # Run Docker container
      - name: Run container
        run: docker run -d -p 5000:5000 flask-app

      # Wait for container
      - name: Wait for container startup
        run: sleep 15

      # Test API
      - name: Test API
        run: curl http://localhost:5000